import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>IntEsports | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <b>Overview</b>
          </p>
          <div>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
          <div className={styles.intesports}>
            Players
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://friendbase.tech"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Join <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Apply to be a Part of IntEsports.
            </p>
          </a>


          <a
            href="https://friendbase.tech"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Legal <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Legal Mumbo-Jumbo and Privacy Policy.
            </p>
          </a>

          <a
            href="https://valorantesports.com/vct-overview"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              VCT <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover News About Valorant Champions Tour.
            </p>
          </a>

          <a
            href="https://friendbase.tech"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              FAQ <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Any Doubt? Seek help and Contact us.
            </p>
          </a>
        </div>

      </main>
    </>
  )
}
